dependencies {
    implementation platform('org.apache.jmeter:ApacheJMeter_bom:5.6.3')
    
    implementation 'org.apache.jmeter:ApacheJMeter_http'
    implementation 'org.apache.jmeter:ApacheJMeter_java'
    implementation 'org.apache.jmeter:ApacheJMeter_config'
    implementation 'org.apache.jmeter:ApacheJMeter_functions'
    implementation 'org.apache.jmeter:ApacheJMeter_components'

    implementation 'commons-io:commons-io'
    implementation 'org.apache.commons:commons-lang3'
}